config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  resources :authors
  resources :categories
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorships
  has_many :books, :through => :authorships
  default_scope { order("name ASC") }

  validates :name, presence: true
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authorships
  has_many :categorizations
  has_many :categories, :through => :categorizations
  has_many :authors, :through => :authorships

  accepts_nested_attributes_for :authors

  validates :name, presence: true

  has_attached_file :image,
                    :default_url => "missing_cover.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  default_scope { order("id DESC") }

end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, :dependent => :destroy
  has_many :books, :through => :categorizations
  validates :name, presence: true

  default_scope { order("name ASC") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  validates :name, presence: true
  after_initialize :set_default_role, if: :new_record?

  enum role: [:user, :admin]

  def set_default_role
    self.role ||= :user
  end

  default_scope { order("name ASC") }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:edit, :update, :destroy, :index, :new, :create]


  def index
    @authors = Author.paginate(page: params[:page])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(author_params)
    if @author.save
      redirect_to authors_url, :flash => { :success => "Author created!" }
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      flash[:success] = "Author updated"
      redirect_to authors_url
    else
      render 'edit'
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    Author.find(params[:id]).destroy
    flash[:success] = "Author deleted"
    redirect_to authors_url
  end

  private

  def author_params
    params.require(:author).permit(:name, :bio)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController
  def create
    @book = Book.find(params[:id])
    @author = Author.find(params[:id])
    @book.add_author!(@author)
    # redirect_to books_url
  end

  def destroy
    @book = Book.find(params[:id])
    @author = Authorship.find(params[:id]).author
    @book.remove_author!(@author)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :index]

  def index
    @books = Book.paginate(page: params[:page])
  end

  def new
    @book = Book.new
    @authors = Author.all
    @categories = Category.all
  end

  def create
    @book = Book.create(book_params)
    @authors = author_params[:authors].reject(&:empty?)
    @categories = category_params[:categories].reject(&:empty?)
    if @book.save
      create_relations

      flash[:success] = "Book created"
      redirect_to books_url, :flash => { :success => "Micropost created!" }
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
    @authors = @book.authors
    @categories = @book.categories
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to books_url
  end

  def edit
    @book = Book.find(params[:id])
    @current_authors = @book.authors
    @current_categories = @book.categories
    @authors = Author.all
    @categories = Category.all
  end

  def update
    @book = Book.find(params[:id])
    @authors = author_params[:authors].reject(&:empty?)
    @categories = category_params[:categories].reject(&:empty?)

    if @book.update_attributes(book_params)
      @book.authorships.destroy_all
      @book.categorizations.destroy_all

      create_relations
      flash[:success] = "Book updated"
      redirect_to books_url
    else
      render 'edit'
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :description, :image)
  end

  def author_params
    params.require(:book).permit(authors: [])
  end

  def category_params
    params.require(:book).permit(categories: [])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def create_relations
    @authors.each do |author|
      @book.authorships.create([book_id: @book.id, author_id: author])
    end

    @categories.each do |category|
      @book.categorizations.create([book_id: @book.id, category_id: category])
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :index]

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to categories_url, :flash => { :success => "Category created!" }
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Category updated"
      redirect_to categories_url
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
   @categories = Category.all
   @books = Book.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:edit, :update, :destroy, :index]


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

  def user_params
     params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :role)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/_authors_form.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-4">
    <%= form_for(@author) do |f| %>
      <div class="form-group">
        <%= f.label :name, class: 'control-label' %><br />
        <%= f.text_field :name, class: 'form-control', autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :bio, class: 'control-label' %><br />
        <%= f.text_area :bio, class: 'form-control' %>
      </div>
      <% if @author.id.nil? %>
        <%= f.submit "Create", class: "btn btn-primary" %>
      <% else %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/authors/edit.html.erb
<h1>Edit author</h1>
<%= render 'authors/authors_form' %>

app/views/authors/index.html.erb
<h1>All authors</h1>
<%= link_to 'Add author', new_author_path, class: 'btn btn-success' %>
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>BIO</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @authors.each do |author| %>
      <tr>
        <td><%= author.id %></td>
        <td><%= link_to author.name, author %></td>
        <td><%= author.bio %></td>
        <td>
          <%= link_to edit_author_path(author),
                      class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to author, method: :delete,
                      data: { confirm: "You sure?" },
                      class: "btn btn-danger" do %>
              <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/authors/new.html.erb
<h1>New author</h1>
<%= render 'authors/authors_form' %>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>
<p><%= @author.bio %></p>

app/views/books/_books_form.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-4">
    <%= form_for(@book) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'control-label' %><br />
          <%= f.text_field :name, class: 'form-control', autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :description, class: 'control-label' %><br />
          <%= f.text_field :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :image, class: 'control-label' %><br />
          <%= f.file_field :image, class: 'form-control' %>
        </div>

        <% unless @book.id.nil? %>
          <div class="form-group">
            <%= f.label 'Current authors:', class: 'control-label' %><br />
            <ul>
              <%= render partial: 'shared/authors', collection: @current_authors %>
            </ul>
            <%= f.label 'Current categories:', class: 'control-label' %><br />
            <ul>
              <%= render partial: 'shared/authors', collection: @current_categories %>
            </ul>
          </div>
        <% end %>

        <%= f.fields_for :authorships do |ff| %>
          <div class="form-group">
            <%= f.label 'Authors (hold ctrl for multiply select)', class: 'control-label' %><br />
            <%= f.select :authors, @authors.collect { |p| [ p.name, p.id ] }, {},
                       { :multiple => true, :size => 5, class: "form-control" } %>
          </div>
        <% end %>


        <%= f.fields_for :categorizations do |ff| %>
          <div class="form-group">
            <%= f.label 'Categories (hold ctrl for multiply select)', class: 'control-label' %><br />
            <%= f.select :categories, @categories.collect { |p| [ p.name, p.id ] }, {},
                       { :multiple => true, :size => 5, class: "form-control" } %>
          </div>
        <% end %>

        <% if @book.id.nil? %>
            <%= f.submit "Create", class: "btn btn-primary" %>
        <% else %>
            <%= f.submit "Update", class: "btn btn-primary" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<h3 class="text-center">Edit <%= @book.name %></h3>
<%= render 'books/books_form' %>

app/views/books/index.html.erb
<h1>All books</h1>
<%= link_to 'Add book', new_book_path, class: 'btn btn-success' %>
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Descriprion</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td><%= book.id %></td>
        <td><%= link_to book.name, book %></td>
        <td><%= book.description%></td>
        <td>
          <%= link_to edit_book_path(book),
                      class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to book, method: :delete,
                      data: { confirm: "You sure?" },
                      class: "btn btn-danger" do %>
              <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/books/new.html.erb
<h3 class="text-center">New book</h3>
<%= render 'books/books_form' %>

app/views/books/show.html.erb
<div class="row">
  <div class="col-lg-4">
    <%= image_tag @book.image, class:'img-responsive img-rounded' %>
  </div>
  <div class="col-lg-8">
    <h1><%= @book.name %></h1>
    <p>Written by:</p>
    <ul>
      <%= render partial: 'shared/authors', collection: @authors %>
    </ul>
    <p>Categories:</p>
    <ul>
      <%= render partial: 'shared/categories', collection: @categories %>
    </ul>
    <p>Descriptin:</p>
    <p><%= @book.description %></p>
  </div>
</div>

app/views/categories/_categories_form.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-4">
    <%= form_for(@category) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'control-label' %><br />
          <%= f.text_field :name, class: 'form-control', autofocus: true %>
        </div>

        <% if @category.id.nil? %>
            <%= f.submit "Create", class: "btn btn-primary" %>
        <% else %>
            <%= f.submit "Update", class: "btn btn-primary" %>
        <% end %>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<h3 class="text-center">Edit <%= @category.name %></h3>
<%= render 'categories/categories_form' %>

app/views/categories/index.html.erb
<h1>All categories</h1>
<%= link_to 'Add category', new_category_path, class: 'btn btn-success' %>
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td>
          <%= link_to edit_category_path(category),
                      class: "btn btn-default" do %>
              <i class="glyphicon glyphicon-pencil"></i>
          <% end %>
          <%= link_to category, method: :delete,
                      data: { confirm: "You sure?" },
                      class: "btn btn-danger" do %>
              <i class="glyphicon glyphicon-trash"></i>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/categories/new.html.erb
<h3 class="text-center">New category</h3>
<%= render 'categories/categories_form' %>

app/views/categories/show.html.erb
<%= render 'pages/main_page' %>

app/views/users/edit.html.erb
<h3>Edit <%= @user.name %></h3>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-sm-10 col-sm-offset-1 col-md-4 col-md-offset-4">
    <%= form_for(@user) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: 'control-label' %><br />
          <%= f.text_field :name, class: 'form-control', autofocus: true %>
        </div>

        <div class="form-group">
          <%= f.label :email, class: 'control-label' %><br />
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div>
          <%= f.check_box :role, {}, 'admin', 'user' %>
          <%= f.label :admin %>
        </div>
        <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= link_to user.name, user %></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to edit_user_path(user),
                          class: "btn btn-default" do %>
                  <i class="glyphicon glyphicon-pencil"></i>
              <% end %>
              <%= link_to user, method: :delete,
                          data: { confirm: "You sure?" },
                          class: "btn btn-danger" do %>
                  <i class="glyphicon glyphicon-trash"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
<%= will_paginate %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>