config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :books
  resources :authors
  resources :categories
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorships
  has_many :books, :through => :authorships
  default_scope { order("name ASC") }

  validates :name, presence: true
end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authorships
  has_many :categorizations
  has_many :categories, :through => :categorizations
  has_many :authors, :through => :authorships

  accepts_nested_attributes_for :authors

  validates :name, presence: true

  has_attached_file :image,
                    :default_url => "missing_cover.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  default_scope { order("id DESC") }

end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, :dependent => :destroy
  has_many :books, :through => :categorizations
  validates :name, presence: true

  default_scope { order("name ASC") }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :books
  validates :name, presence: true
  after_initialize :set_default_role, if: :new_record?

  enum role: [:user, :admin]

  def set_default_role
    self.role ||= :user
  end

  default_scope { order("name ASC") }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:edit, :update, :destroy, :index, :new, :create]


  def index
    @authors = Author.paginate(page: params[:page])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(author_params)
    if @author.save
      redirect_to authors_url, :flash => { :success => "Author created!" }
    else
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(author_params)
      flash[:success] = "Author updated"
      redirect_to authors_url
    else
      render 'edit'
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def destroy
    Author.find(params[:id]).destroy
    flash[:success] = "Author deleted"
    redirect_to authors_url
  end

  private

  def author_params
    params.require(:author).permit(:name, :bio)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :index]

  def index
    @books = Book.paginate(page: params[:page])
  end

  def new
    @book = Book.new
    @authors = Author.all
    @categories = Category.all
  end

  def create
    @book = Book.create(book_params)
    @authors = author_params[:authors].reject(&:empty?)
    @categories = category_params[:categories].reject(&:empty?)
    if @book.save
      create_relations

      flash[:success] = "Book created"
      redirect_to books_url, :flash => { :success => "Micropost created!" }
    else
      render 'new'
    end
  end

  def show
    @book = Book.find(params[:id])
    @authors = @book.authors
    @categories = @book.categories
  end

  def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book deleted"
    redirect_to books_url
  end

  def edit
    @book = Book.find(params[:id])
    @current_authors = @book.authors
    @current_categories = @book.categories
    @authors = Author.all
    @categories = Category.all
  end

  def update
    @book = Book.find(params[:id])
    @authors = author_params[:authors].reject(&:empty?)
    @categories = category_params[:categories].reject(&:empty?)

    if @book.update_attributes(book_params)
      @book.authorships.destroy_all
      @book.categorizations.destroy_all

      create_relations
      flash[:success] = "Book updated"
      redirect_to books_url
    else
      render 'edit'
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :description, :image)
  end

  def author_params
    params.require(:book).permit(authors: [])
  end

  def category_params
    params.require(:book).permit(categories: [])
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def create_relations
    @authors.each do |author|
      @book.authorships.create([book_id: @book.id, author_id: author])
    end

    @categories.each do |category|
      @book.categorizations.create([book_id: @book.id, category_id: category])
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :index]

  def index
    @categories = Category.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)
    if @category.save
      redirect_to categories_url, :flash => { :success => "Category created!" }
    else
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books
  end

  def destroy
    Category.find(params[:id]).destroy
    flash[:success] = "Category deleted"
    redirect_to categories_url
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      flash[:success] = "Category updated"
      redirect_to categories_url
    else
      render 'edit'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :description)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
   @categories = Category.all
   @books = Book.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_user, only: [:edit, :update, :destroy, :index]


  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end


  private

  def user_params
     params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation, :role)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Library", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if signed_in? %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
               aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>

        </ul>

        <% if current_user.admin? %>
          <ul class="nav navbar-nav">
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Books", books_path %></li>
            <li><%= link_to "Authors", authors_path %></li>
            <li><%= link_to "Categories", categories_path %></li>
          </ul>
        <% end %>

      <% end  %>

      <!--<form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->



    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/_main_page.html.erb
<!-- Page Content -->
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <p class="lead">Categories</p>
      <%= link_to 'All', root_path, class: 'list-group-item' %>
      <%= render partial: 'shared/categories_nav', collection: @categories %>
    </div>

    <div class="col-md-9">
      <p class="lead"><%= @category? @category.name : 'All' %></p>
      <div class="row">
        <%= render partial: 'shared/book', collection: @books %>
      </div>
    </div>
  </div>
</div>
<!-- /.container -->

app/views/pages/_welcome_message.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h1>Library</h1>
    <p>This is a simple(or not) test application</p>
    <div><%= link_to "Sign up now!", new_user_registration_path, class: 'btn btn-primary btn-lg' %></div>
    <div>Already have account? <%= link_to "Log in", new_user_session_path %></div>
  </div>
</div>

app/views/pages/index.html.erb
<% if signed_in? %>
  <%= render 'pages/main_page' %>
<% else %>
  <%= render 'pages/welcome_message' %>
<% end  %>

app/views/pages/welcome.html.erb
<% if signed_in? %>
  <%= render 'pages/main_page' %>
<% else %>
  <%= render 'pages/welcome_message' %>
<% end  %>

app/views/shared/_authors.html.erb
<li><%= authors.name %></li>

app/views/shared/_book.html.erb
<div class="col-sm-3 col-lg-3 col-md-3">
  <div class="thumbnail">
    <%= image_tag book.image, class: 'img-responsive img-rounded' %>
    <div class="caption">
      <h4><%= link_to book.name, book %></h4>
    </div>
  </div>
</div>

app/views/shared/_categories.html.erb
<li><%= categories.name %></li>

app/views/shared/_categories_nav.html.erb
<%= link_to categories_nav.name, categories_nav, class: 'list-group-item' %>